### ISSUE TITLE
Sugestão: Paginação com API

### ISSUE THREAD

**Issue by eullercristian** [mauri870/api-skeleton-laravel#1]
Mauri, gostaria de deixar uma sugestão de implementação neste repositório. Poderia demonstrar como esta api funcionaria utilizando paginação?

**Comment by mauri870** [comment]
O vedovelli tem dois videos sobre paginacao com vuejs, uma basica e uma mais avancada.
Se vc se refere a como retornar a resposta da paginacao, realmente e algo q n havia reparado, pq se vc retornar via apiResponse vai ficar com objetos data duplicados, vou atualizar pra retornar corretamente a paginacao e adicionar uma secao no readme, thanks
